###
# GET all planted trees
GET http://localhost:3000/api/planted-trees
###

###
# GET one planted tree by ID
GET http://localhost:3000/api/planted-trees/1
###

###
# POST a new planted tree
POST http://localhost:3000/api/planted-trees
Content-Type: application/json

{
  "catalogTreeId": 1,
  "orderId": 1,
  "personalName": "Mon premier chêne",
  "plantingDate": "2025-07-01",
  "plantingPlace": "Jardin de l'Orangerie, Strasbourg, France"
}
###

###
# PATCH (update) a planted tree
PATCH http://localhost:3000/api/planted-trees/1
Content-Type: application/json

{
  "personalName": "Mon premier chêne majestueux"
}
###

###
# DELETE a planted tree
DELETE http://localhost:3000/api/planted-trees/1
###