
###
# GET all regions
GET http://localhost:3000/api/regions
###

###
# GET one region by ID
GET http://localhost:3000/api/regions/1
###

###
# POST a new region
POST http://localhost:3000/api/regions
Content-Type: application/json

{
  "name": "Alsace"
}
###

###
# PATCH (update) a region
PATCH http://localhost:3000/api/regions/1
Content-Type: application/json

{
  "name": "Nouvelle-Aquitaine"
}
###

###
# DELETE a region
DELETE http://localhost:3000/api/regions/1
###

###
# GET catalog trees for a region
GET http://localhost:3000/api/regions/1/catalog-trees
###
