###
# GET all users
GET http://localhost:3000/users
###

###
# GET one user
GET http://localhost:3000/users/1
###

###
# POST create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "john_doe",
  "email": "john@example.com",
  "password": "secret123"
}
###

###
# PATCH update user
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
  "email": "john.new@example.com"
}
###

###
# DELETE user
DELETE http://localhost:3000/users/1
###
