###
# GET all users
GET http://localhost:3000/api/users
###

###
# GET one user by ID
GET http://localhost:3000/api/users/1
###

###
# PATCH update user
PATCH http://localhost:3000/api/users/1
Content-Type: application/json

{
  "email": "jane.doe.new@example.com"
}

# Exemple de mise à jour du rôle :
# PATCH http://localhost:3000/api/users/1
# Content-Type: application/json
#
# {
#   "role": "admin"
# }
###

###
# DELETE one user
DELETE http://localhost:3000/api/users/1
###